### ISSUE TITLE
Chain calls cannot be implemented

### ISSUE THREAD

**Issue by cooboyno111** [Samsung/iotjs#1292]
I want to implement exact chain calls in iotjs. Here are the test cases. Just read several files in chained form. The file name can be modified by itself. This code works normally in nodejs. I opened the es2015-subset. So Promise is available. Parallel code is normally called and serial is not.

```javascript
var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
    fs.readFile(fileName, function(error, data){
      if (error) reject(error);
        console.log(data.toString());      
        resolve(data);      
    });
  });
};
code ERR:
readfile('test.csv').then(function() {
    readfile('NMap.ts').then(function() {
        readfile('NMap.js').then(function() {
             readfile('test.csv').then(function() {
             console.log(Date.now());
           })
        })
    })
})
code OK:
var tasks=[];
tasks.push(readfile('test.csv'));
tasks.push(readfile('NMap.ts'));
tasks.push(readfile('NMap.js'));
tasks.push(readfile('test.csv'));
Promise.all(tasks).then(function () {
      console.log(new Date());
});
```

**Comment by glistening** [comment]
@cooboyno111 There was a bug on `Promise.then` in jerryscrip  and fixed. I think updating submodule should fix this issue. The example in https://github.com/jerryscript-project/jerryscript/issues/2060

```js
var p = Promise.resolve(1).then(function(x) {
    print(x) // will print 1
    return Promise.resolve(2)
  }).then(function(x) {
    print(x) // should print 2, but now this will not be executed
  })
```

works well after updating submodule.

**Comment by glistening** [comment]
@cooboyno111 #1295 is landed. Could you please update and check your test again?

**Comment by cooboyno111** [comment]
@glistening 
The latest code can only implement 2 layer chain call。Like the previous example, it can only read second files.（test.csv，NMap.ts）。3-4 No execution and no error reporting. The code is ignored.
NODEJS reads all four files。（test.csv，NMap.ts，NMap.js，test.csv）
It's basically enough for a IOT device. But I believe you can do better。

**Comment by glistening** [comment]
@cooboyno111 Thank you for testing. I still think this bug is likely related to Promise implementation. Could you try to make a complete test case for jerryscript? If it does not work, you could write an issue on jerryscript repository.

**Comment by cooboyno111** [comment]
@glistening I compared iotjs jerryscript. Found that the problem did not appear in the jerryscript. It can achieve multi-level chain callback. I tested the 5 layer. This problem may appear in the fs.readFile method. The code in my Promise. Even the implementation of the 100000 console.log no problem. If you use the fs.readFile method of single layer two is wrong. I think this problem is not in the Promise implementation. There may be fs.readFile and Promise conflict.

test code 
var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
      for(var i=0;i<100000;i++){
         console.log("readfile----------------------------------------"+fileName);
      }
      console.log("readfile----------------------------------------"+fileName);
      resolve(fileName);      
/* error code
    fs.readFile(fileName, function(error, data){
      if (error) reject(error);
        console.log(data.toString());   
        console.log(fileName+"--------------------------------------");    
        resolve(fileName);      
    });*/
  });
};
readfile('1.txt').then(function() {
    readfile('2.txt').then(function() {
        readfile('3.txt').then(function() {
             readfile('4.txt').then(function() {
             readfile('1.txt').then(function() {
              console.log(Date.now());
              })
           })
        })
    })
})

**Comment by glistening** [comment]
@cooboyno111 Thank you again for investigation. We will investigate it.

**Comment by glistening** [comment]
@cooboyno111 I ran the source above using node and iotjs. I cannot find differences. It behaves similarly. 

```
$ ./build/x86_64-linux/debug/bin/iotjs t.js
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
1509671760400.1

1.txt--------------------------------------

2.txt--------------------------------------

3.txt--------------------------------------

4.txt--------------------------------------

1.txt--------------------------------------
```

```
$ node t.js
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
1509671979840

1.txt--------------------------------------

2.txt--------------------------------------

3.txt--------------------------------------

4.txt--------------------------------------

1.txt--------------------------------------
```

I ran the code with enabling the code enclosed with comment.

The last lines changed nondeterministically both of node and iotjs  like followings:

```
$ node t.js
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
1509671979840

1.txt--------------------------------------

2.txt--------------------------------------

3.txt--------------------------------------

4.txt--------------------------------------

1.txt--------------------------------------
$ node t.js
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
1509671980400

1.txt--------------------------------------

4.txt--------------------------------------

2.txt--------------------------------------

1.txt--------------------------------------

3.txt--------------------------------------
```

Could you let me know what is the problem in detail?

**Comment by cooboyno111** [comment]
@glistening 
var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
/* //Execute correctly
      for(var i=0;i<100000;i++){
         console.log("readfile----------------------------------------"+fileName);
      }
      console.log("readfile----------------------------------------"+fileName);
      resolve(fileName);      
*/
//Error executing
    fs.readFile(fileName, function(error, data){
      if (error) reject(error); 
        console.log(fileName+"--------------------------------------");
	console.log(data.toString());      
        resolve(fileName);      
    });
  });
};
readfile('1.txt').then(function() {
    readfile('2.txt').then(function() {
        readfile('3.txt').then(function() {
             readfile('4.txt').then(function() {
                readfile('1.txt').then(function() {
                  console.log(Date.now());
              })
           })
        })
    })
})

my log
//////////////////////////////iotjsjs//////////////////////
./iotjs iotbug.js 
1.txt--------------------------------------
11111111

2.txt--------------------------------------
22222222
//////////////////////////////nodejs//////////////////////
node iotbug.js 
1.txt--------------------------------------
11111111

2.txt--------------------------------------
22222222

3.txt--------------------------------------
33333333

4.txt--------------------------------------
444444444444

1.txt--------------------------------------
11111111

1509677452261

build cmd：./tools/build.py --jerry-profile es2015-subset

You really need to create several text files and fill in some data.

**Comment by glistening** [comment]
@cooboyno111 
Build command are same. I created several text files by `$ touch {1..4}.txt`
I tested again with filled some data as you suggested. The results are same to `node`, too.
Here are my log. For your information, I build and test on x86_64.
I also checked the results are same `--buildtype=debug` and `--buildtype=release`.

```
$ ./build/x86_64-linux/debug/bin/iotjs t.js
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
1509683555549.722
1111

1.txt--------------------------------------
2222

2.txt--------------------------------------
3333

3.txt--------------------------------------
4444

4.txt--------------------------------------
1111

1.txt--------------------------------------

$ node t.js
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------2.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------3.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------4.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
readfile----------------------------------------1.txt
1509683585003
1111

1.txt--------------------------------------
2222

2.txt--------------------------------------
3333

3.txt--------------------------------------
4444

4.txt--------------------------------------
1111

1.txt--------------------------------------
```

Here is my test code copied from yours and add indentation.

```js
var fs = require('fs');
function readfile(fileName) {
  return new Promise(function(resolve, reject) {
    for (var i=0; i<2; i++) {
      console.log('readfile----------------------------------------'+fileName);
      }
      console.log('readfile----------------------------------------'+fileName);
      resolve(fileName);
      // error code
      fs.readFile(fileName, function(error, data){
      if (error) reject(error);
      console.log(data.toString());
      console.log(fileName+"--------------------------------------");
      resolve(fileName);
    });
  });
}
readfile('1.txt').then(function() {
  readfile('2.txt').then(function() {
   readfile('3.txt').then(function() {
     readfile('4.txt').then(function() {
       readfile('1.txt').then(function() {
         console.log(Date.now());
       });
     });
   });
 });
});
```

**Comment by cooboyno111** [comment]
@glistening 
function readfile(fileName) {
  return new Promise(function(resolve, reject) {
    for (var i=0; i<2; i++) {
      console.log('readfile----------------------------------------'+fileName);
      }
      console.log('readfile----------------------------------------'+fileName);
      //resolve(fileName);//if Delete this line and make a mistake
      // error code
      fs.readFile(fileName, function(error, data){
      if (error) reject(error);
      console.log(data.toString());
      console.log(fileName+"--------------------------------------");
      resolve(fileName);
    });
  });
}

**Comment by glistening** [comment]
@cooboyno111 I still can't figure out what is problem and how to run from code above. Could you push full example source that I can run immediately, not code segment. It is difficult to read, If possible could you push your code with proper indentation?

**Comment by cooboyno111** [comment]
var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
    fs.readFile(fileName, function(error, data){
      if (error){
          reject("error");
        }else{
	  console.log(data.toString());      
          resolve(fileName);
        }      
    });
  });
};
function loadfi(arr,index){
readfile(arr[index]).
then(function() {
console.log("loadfinal-"+arr[index]);
index++;
loadfi(arr,index)
}).catch(function(e) {
console.log("error--"+e.message);
})
}
var arr=['1.txt','2.txt','3.txt','4.txt']
loadfi(arr,0);

**Comment by cooboyno111** [comment]
Correct execution code

var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
    if(fileName===undefined)  reject("error");
    console.log(fileName); 
    resolve(fileName);
  });
};
function loadfi(arr,index){
readfile(arr[index]).
then(function() {
console.log("loadfinal-"+arr[index]);
index++;
loadfi(arr,index)
}).catch(function(e) {
console.log("error--"+e.message);
})
}
var arr=['1.txt','2.txt','3.txt','4.txt']
loadfi(arr,0);

**Comment by glistening** [comment]
@cooboyno111 I ran your test code.

**test code**
```js
var fs = require('fs')
function readfile(fileName){
  return new Promise(function (resolve, reject){
    fs.readFile(fileName, function(error, data){
      if (error){
        reject("error");
      }else{
        console.log(data.toString());
        resolve(fileName);
      }
    });
  });
};
function loadfi(arr,index){
  readfile(arr[index]).
    then(function() {
      console.log("loadfinal-"+arr[index]);
      index++;
      loadfi(arr,index)
    }).catch(function(e) {
      console.log("error--"+e.message);
    })
}
var arr=['1.txt','2.txt','3.txt','4.txt']
loadfi(arr,0);
```

**result from nodejs and iotjs:**
```sh
$ node 1292x.js
111

loadfinal-1.txt
222

loadfinal-2.txt
333

loadfinal-3.txt
444

loadfinal-4.txt
error--path must be a string or Buffer
brian:~/iotjs/iotjs$ ./build/x86_64-linux/debug/bin/iotjs 1292x.js
111

loadfinal-1.txt
222

ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at /home/brian/iotjs/iotjs/deps/jerry/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):43.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

I found assertion failure in jerryscript. We will investigate more.

**Comment by LaszloLango** [comment]
@glistening @cooboyno111 I've checked this issue. It looks like the error is somewhere here: https://github.com/Samsung/iotjs/blob/master/src/iotjs.c#L159
I think we exit the loop too early. Chain calls work perfectly with sync calls. For example using `fs.readFileSync` instead of `fs.readFile`. I'll continue the investigation.

**Comment by LaszloLango** [comment]
@cooboyno111 for a temporary workaround you can count the started and settled Promise objects by yourself and don't let the program to exit until there are any pending Promise job. For example the following code works for your use case:
```js
var pendingPromiseObj = 0;

var fs = require('fs')
function readfile(fileName) {
  return new Promise(function (resolve, reject) {
    pendingPromiseObj++;
    fs.readFile(fileName, function(error, data) {
      if (error) {
        console.log("error");
        reject("error");
      } else {
        console.log(data.toString());
        resolve(fileName);
      }
    });
  });
};

function loadfi(arr,index) {
  readfile(arr[index]).
    then(function() {
      console.log("loadfinal-" + arr[index]);
      index++;
      loadfi(arr,index)
      pendingPromiseObj--;
    }).catch(function(e) {
      console.log("error--" + e.message);
      pendingPromiseObj--;
    })
}

var arr = ['1.txt', '2.txt', '3.txt'];
loadfi(arr, 0);

var interval = setInterval(function(){
  console.log("pendingPromiseObj: " + pendingPromiseObj);
  if (pendingPromiseObj == 0) {
    clearInterval(interval);
  }
}, 10);
```

**output:**
```
1111
loadfinal-1.txt
2222

loadfinal-2.txt
pendingPromiseObj: 1
3333

loadfinal-3.txt
error--Bad arguments: undefined
pendingPromiseObj: 0
```

**Comment by LaszloLango** [comment]
@cooboyno111 @glistening I've made a fix for this. Please check #1307

**Comment by cooboyno111** [comment]
@LaszloLango @glistening 
i test commit 4906d111a0ea642decb5894b30accd129b067def
The problem has been corrected.
When is your next release release?

**Comment by glistening** [comment]
@cooboyno111 Currently the next official release date is not fixed.
